remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

title: bepa
description: Beatriz E. Palacios Abad, PhD

logo: /assets/images/profile-pic.jpg

linkedin: 'https://https://www.linkedin.com/in/bepa/'
scholar: 'https://scholar.google.com/citations?user=0ZR4eUgAAAAJ'